# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/steve_nbdev_train.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/steve_nbdev_train.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/steve_nbdev_train.ipynb 10
def foo(): pass
